name: Go Build Workflow

on:
  push:
    branches:
      - main

jobs:
  BuildGo:
    runs-on: ubuntu-latest
    env:
      FILE_NAME: hello-server
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build for Linux
        run: go build ${{ env.FILE_NAME }}.go

      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build ${{ env.FILE_NAME }}.go

      - name: Upload artifact for Linux
        uses: actions/upload-artifact@v1.0.0
        with:
          name: linux
          path: ./${{ env.FILE_NAME }}

      - name: Upload artifact for Windows
        uses: actions/upload-artifact@v1.0.0
        with:
          name: windows
          path: ./${{ env.FILE_NAME }}.exe
