name: Go Build Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/15 * * * 1-6'

jobs:
  build-go:
    runs-on: ubuntu-latest
    env:
      FILE_NAME: hello-server
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build for Linux
        run: go build -o ${{ env.FILE_NAME }}.out ${{ env.FILE_NAME }}.go

      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -o ${{ env.FILE_NAME }}.exe ${{ env.FILE_NAME }}.go

      - name: Upload artifact for Linux
        uses: actions/upload-artifact@v1.0.0
        with:
          name: linux
          path: ./${{ env.FILE_NAME }}.out

      - name: Upload artifact for Windows
        uses: actions/upload-artifact@v1.0.0
        with:
          name: windows
          path: ./${{ env.FILE_NAME }}.exe

  download-and-run-linux:
    runs-on: ubuntu-latest
    needs: build-go
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Linux Artifact
        uses: actions/download-artifact@v2
        with:
          name: linux

      - name: List files in workspace
        run: ls -al

      - name: Create directory if not exists
        run: mkdir -p ./linux

      - name: List files in linux directory
        run: ls -al ./linux

      - name: Move artifact to expected path
        run: mv ./${{ env.FILE_NAME }}.out ./linux/

      - name: List files in linux directory after move
        run: ls -al ./linux

      - name: Run Script
        run: source ./linux/run.sh
